name: Copy the "About" Page from the profile readme repo

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # This will run the workflow daily at midnight UTC
  workflow_dispatch: # Run manually

jobs:
  download-and-copy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download index.html from profile readme repo
        run: curl -o about.html https://spageektti.cc/spageektti/index.html

      - name: Check for changes
        id: changes
        run: |
          git fetch
          if git diff --exit-code about.html; then
            echo "No changes detected"
            echo "::set-output name=changed::false"
          else
            echo "Changes detected"
            echo "::set-output name=changed::true"
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add about.html
          git commit -m 'Update about.html from spageektti.cc/spageektti'
          git push
